SET C51INC=C:\Keil_v5\C51\Inc;C:\Keil_v5\C51\Inc\Abov
SET C51LIB=C:\Keil_v5\C51\Lib
SET CPU_TYPE=A94B114
SET CPU_VENDOR=ABOV Semiconductor
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x00B71B00
"C:\Keil_v5\C51\BIN\AX51.EXE" @".\out\STARTUP._ia"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\out\Main.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\out\Clock.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\out\Timer.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\out\I2C.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\out\A94B11~1.__I"
"C:\Keil_v5\C51\BIN\AX51.EXE" @".\out\A94B11~1._IA"
"C:\Keil_v5\C51\BIN\LX51.EXE" @".\out\A94B11~1.LNP"
"C:\Keil_v5\C51\BIN\OHX51.EXE" ".\out\A94B114_TIMER0_PGM" HEX
